### ISSUE TITLE
Support testing multiple models for the same provider

### ISSUE THREAD

**Issue by lchiquitto** [ASRBench/asrbench#1]
The system must support testing of multiple models (and also different parameters) with the same "provider". Currently the config file format will not allow this.

Example: suppose I want to test faster_whisper with models medium and large.

```
providers:
  faster_whisper:
    model_size: "medium"
    compute_type: "int8"
    device: "cpu"
    beam_size: 5
  faster_whisper:
    model_size: "large"
    compute_type: "int8"
    device: "cpu"
    beam_size: 5
```

The second faster_whisper block will overwrite the first.

I suppose there are more than one way to support this. One is to change the "providers" section to be like the "datasets" section. Example:

```
providers:
  fw_medium:
    provider: "faster_whisper"
    model_size: "medium"
    compute_type: "int8"
    device: "cpu"
    beam_size: 5
  fw_large:
    provider: "faster_whisper"
    model_size: "large"
    compute_type: "int8"
    device: "cpu"
    beam_size: 5
```

**Comment by lchiquitto** [comment]
Perhaps an even cleaner approach would be:

```
benchmarks:
  faster_whisper_medium_cpu:
    provider: "faster_whisper"
    model_name: "medium"
    compute_type: "int8"
    device: "cpu"
    beam_size: 5
  faster_whisper_medium_gpu:
    provider: "faster_whisper"
    model_name: "medium"
    compute_type: "int8_float16"
    device: "cuda"
    beam_size: 5
  whisper_turbo_gpu:
    provider: "whisper"
    model_name: "large-v3-turbo"
    device: "cuda"
    language: "pt"
    fp16: False
```
But I'm sure this would require more intrusive changes.
