### ISSUE TITLE
Config parameter for language

### ISSUE THREAD

**Issue by lchiquitto** [ASRBench/asrbench#4]
Most providers allow the user to indicate which language should be used (instead of relying on the model to identify it). FasterWhisper's transcribe(), for example, allows for an optional "language" parameter.

Suggestion/example:

```
providers:
  faster_whisper_1:
    provider: "faster_whisper"
    model: "medium"
    compute_type: "int8_float16"
    device: "cuda"
    beam_size: 1
    language: "pt"
```
